---
title: "Text editors and IDEs"
author: "David Benkeser, PhD MPH<br> <span style = 'font-size: 50%;'> Emory University<br> Department of Biostatistics and Bioinformatics </span>"
date: 'Introduction Reproducible Workflows in R<br><br>`r renv::activate("../.."); fontawesome::fa("link", fill = '#ffffff')` [.white[bit.ly/intro_repro_workflo]](https://bit.ly/intro_repro_workflo) <br> `r fontawesome::fa("book", fill = '#ffffff')` [.white[Additional reading]](https://benkeser.github.io/intro_repro_workflo/readings#text-editors)'
tldr: "Give me a good text editor, or give me death."
recording: ""
start: "0:0:0"
breakoutsoln: ""
reading: "text-editors"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature: 
      titleSlideClass: ["left", "middle", "inverse"]
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
# define a class for a block of text with mono spaced print
extra_css <- list(
  ".monobox" = list(
    display = "inline-block", 
    width = "90%",
    height = "400px",
    padding = "5px",
    border = "1px solid #012169",
    `background-color` = "#d9d9d6",
    `font-family` = "Courier Prime",
    `align-items` = "left",
    `vertical-align` = "middle"
  ),
  ".red" = list(color = "#da291c",
                `font-weight` = "600"),
  ".small" =  list(`font-size` = "80%"),
  ".large" =  list(`font-size` = "150%"),
  "ul li" = list(`margin-bottom` = "10px"),
  "a" = list(color = "#007dba"),
  "a:hover" = list("text-decoration" = "underline")
)

style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime"),
  extra_css = extra_css
)
```
<style type="text/css">
.remark-slide-content {
    font-size: 23px
}
</style>

## Important principle 

.center[
  .large[
    Don't touch that mouse!
  ]
]

???

Pointing-and-clicking is not reproducible! 

Moreover, every time you have to reach for the mouse, there's a 
loss of efficiency. Saving 1 second on something you do 50 times a
day means saving about five hours per year. You're going to be writing
code the rest of your career. Ten years from now, do you want to look
back and realize you spent two days of time reaching to and from your mouse?

---

## Editors and IDEs

A good text editor...
* does not require pointing and clicking;
* makes it easy to send code to a REPL;
* has syntax highlighting;
* indents code automatically;
* simultaneously view code across files;
* has a full suite of (customizable) hot keys.

An __integrated development environment (IDE)__ provides additional tools.
* Text editor + REPL/s + debugging tools
* REPL = place to execute code interactively (e.g., R Console)

???

The choice of an editor/IDE is personal. Some people take the choice of editor
far too seriously. Most editors/IDEs these days can be customized in myriad ways, 
such that the difference between editors is becoming smaller. 

---

## Good editors/IDEs

* [R Studio](https://www.rstudio.com/products/rstudio/download/)
* [Sublime Text](https://www.sublimetext.com/)
* [VS Code](https://code.visualstudio.com/)
* [atom](https://atom.io/)
* [Notepad++](https://notepad-plus-plus.org/downloads/)
* [vim](https://www.vim.org/)
* [emacs](https://www.gnu.org/software/emacs/)

I personally use Sublime Text 97% and vim 3%. 
* Work remotely on Unix systems? Know *at least some* vim or emacs.

I will use __R Studio__ for this course, because I suspect it is the most familiar editor to many.

???

See [course readings](https://benkeser.github.io/intro_repro_workflo/readings#text-editors) for more resources. 
