---
title: "Front Matter"
author: "David Benkeser, PhD MPH<br> <span style = 'font-size: 50%;'> Emory University<br> Department of Biostatistics and Bioinformatics </span>"
date: 'Introduction Reproducible Workflows in R<br><br>`r renv::activate("../.."); fontawesome::fa("link", fill = '#ffffff')` [.white[bit.ly/intro_repro_workflo]](https://bit.ly/intro_repro_workflo)'
tldr: "Nuts and bolts of the course."
recording: "91596f73-024b-4e58-93ae-ad90011887f7"
reading: ""
breakoutsoln: ""
start: "0:0:0"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      titleSlideClass: ["left", "middle", "inverse"]
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
extra_css <- list(
    "ul" = list(`margin-bottom` = "0.5em",
      `margin-top` = "0.5em"),
  	"p" = list(`margin-bottom` = "0.25em"),
	"ul li" = list(`margin-bottom` = "10px"),
	"a" = list(color = "#007dba"),
	"a:hover" = list("text-decoration" = "underline"),
	".green" = list(color = "#348338"),
	".red" = list(color = "#da291c")
)

style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime"),
  extra_css = extra_css
)
```

<style type="text/css">
.remark-slide-content {
    font-size: 22px
}
</style>

## Basics

* __Course website__: https://benkeser.github.io/intro_repro_workflo
* __Location__: See course announcement for Zoom link

???

All material for class is available via the course website. The website is hosted on GitHub and all materials are available at the GitHub repository (https://github.com/benkeser/intro_repro_workflo). 

---

## Etiquette

Please use Q and A feature to __ask questions__.
* Speaking into the Zoom void is lonely 😢

Please feel free to ask __any question__ you like. 
* Clarification questions are __always welcome__.
* Enrichment questions will be answered __time-permitting__.

---

## Learning objectives

* Understand why automation is a key element of reproducible data science.
* Perform simple command line operations including running R scripts and compiling R markdown reports.
* Use best coding practices and deliberate project organization to improve reproducibility of workflows.
* Use simple Makefiles to document dependencies in code and produce automated workflows.

---

## What this short course is

A class to...
* __make your life easier__;
* make your science more __reproducible__;
* help increase scientific impact by making code __accessible__ and __readable__;
* __survey a few tools__ that help to these ends;
* provide you the __knowledge base__ to learn more about these tools.

???

The goal is to teach best practices that we should strive for in our 
work and to provide motivation and brief introduction to the tools that 
enable us to make that happen. 

---

## What this short course is .red[not]

A class...
* on machine learning;
* on statistics, really;
* that extensively covers any one area in great depth;
* where you will learn absolutely everything that you need to know to use this stuff in practice.

???

We will not discuss statistical methodology, though I may at 
times show some basic statistics to illustrate software. 

Learning these tools requires practice and (often a great deal of) 
frustration -- it's part of the process. Thankfully, there is a 
large online community that you can access if you know how. Learning
to google efficiently is surprisingly important. 

---

## Format of shortcourse

The course will primarily be lectures and coding demonstrations.

I recommend that during the live sessions, students:
* focus on the __what__ and __why__;
* less focus on the __how__;
* do not (neccessarily) try to follow along with live coding demos.

__Recordings will be made available after the course__.
* revisit recordings or source code for specific syntax

---

## Slides

The slides are created using the [xaringan](https://slides.yihui.org/xaringan/#1) package. 

To print the notes as a .pdf (allegedly works best using Chrome):

* scroll through all slides so content loads;
* File: Print (or `super + p`): Destination: Save as PDF.

The slides contain additional "presenter" notes. 

* Makes the material more self-contained. 
* Makes sure I do not forget to tell you important things.
* To view, enter *Presenter Mode* by pressing `p`.

???

`super` means `Cntrl` on Windows and `Command` on Mac

---

## Schedule

__Day 1__
* Motivation