---
title: "Project organization"
author: "David Benkeser, PhD MPH<br> <span style = 'font-size: 50%;'> Emory University<br> Department of Biostatistics and Bioinformatics </span>"
date: 'Introduction Reproducible Workflows in R<br><br>`r renv::activate("../.."); fontawesome::fa("link", fill = '#ffffff')` [.white[bit.ly/intro_repro_workflo]](https://bit.ly/intro_repro_workflo) <br> `r fontawesome::fa("book", fill = '#ffffff')` [.white[Additional reading]](https://benkeser.github.io/intro_repro_workflo/readings#project-organization)'
tldr: "Choose an organization structure that sparks joy."
recording: ""
start: "0:0:0"
reading: "project-organization"
breakoutsoln: ""
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      titleSlideClass: ["left", "middle", "inverse"]
      highlightStyle: tomorrow-night-blue
      highlightLanguage: rmarkdown
      highlightLines: false
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

extra_css <- list(
  ".small" =  list(`font-size` = "80%"),
  ".large" =  list(`font-size` = "150%"),
  "ul li" = list(`margin-bottom` = "10px"),
  ".red" = list(color = "#da291c",
                `font-weight` = "600"),
  ".green" = list(color = "#348338",
                `font-weight` = "600"),
  ".usera" = list(color = "#006c5b", `font-weight` = "600"),
  ".userb" = list(color = "#6d2077", `font-weight` = "600"),
  ".code-box" = list(display = "inline-block", 
    width = "95%",
    `line-height` = "1em",
    padding = "5px",
    `font-size` = "80%",
    `background-color` = "#f6f6f6",
    `align-items` = "left",
    `font-family` = "Courier Prime",
    border = "1px solid black"),
  "ul" = list(`margin-bottom` = "0.5em",
              `margin-top` = "0.5em"),
  "p" = list(`margin-bottom` = "0.25em")
)

style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime"),
  extra_css = extra_css
)
```

<style type="text/css">
.remark-slide-content {
    font-size: 25px
}
</style>

### Learning objectives

1. Define the major principles of project-based organization.
2. Distinguish between absolute and relative paths as it relates to reproducibility.
3. Identify the role the `here` package plays in file path management.
4. Describe the benefits of modularity in code.

---

### Learning objectives: redux

1. Reorganize projects using the command line.
2. Edit absolute file paths in `R` scripts and R Markdown documents to be relative using the `here` package.

---

background-color: #007dba
class: title-slide, center, inverse, middle

*File organization and naming are powerful weapons against chaos.*
<div> [Jenny Bryan](https://jennybryan.org/)

???

Project organization may seem a rather dull/pedantic topic, but it is actually very important!

---

### Basic principles

__Major suggestions__
* Be consistent across projects.
* Raw data are sacred. Keep them separate from everything else.
* Separate code and data.
* .red[Put everything in one directory.]
* .red[No absolute filepaths in code.]
* Modularize code.

__Other suggestions__
* `Makefile`'s and/or READMEs to document dependencies.
* No spaces in file names. 
* Use meaningful file names.
* Use YYYY-MM-DD date formatting.
* Use a package management system.

???

There is not one correct way to organize a project, but there are many incorrect ways. Over time you will develop your own system for doing so. We'll discuss a few frameworks that may be helpful. 

The biggest thing is to commit to using the same structure for as long as its working for you. As you are working on many projects, be self-aware during the process. Are you consistently losing track of certain types of files? Are there gaps in the workflow that make things hard to reproduce? What can you do to fill in the gaps?

---

background-color: #84754e
class: title-slide, center, inverse, middle

*You mostly collaborate with yourself, and me-from-two-months-ago never responds to email.*
<div> [Karen Cranston](http://kcranston.github.io/)

???

This is as much for preserving your own sanity as it is about being reproducible (though it is about that too). There's a (big) upfront cost here, but in the end it is worth it. 

---

### What to organize?

Depending on the nature of the project, the organization system may look different.
* E.g., data analysis vs. methods paper vs. presentation vs. web app vs. etc...

The systems should adhere to the same general principles, but different requirements may necessitate different structures. 

.red[Think about organization of a project from the outset!]

???

Thinking about project organization from the outset is the most important thing. Map out (e.g., as comments in a README) how you see the project developing. Even if things change over time, it's good to have a structure in place from the beginning. 

This pertains to project directories in particular, but also to your hard drive in general. I made the mistake of organizing projects by institution (UW, Berkeley, Emory), but am now regretting that. What about projects that weren't finished when I got to Emory? What about projects that I continued developing once I got here. It's a mess. Don't be like me. 

---

### Organizing data

Raw data are sacred... but may be a mess. 
* You'll be surprised (and disheartened) by how many color-coded excel sheets you'll get in your life.

Tempting to edit raw data by hand. .red[Don't!]
* Everything scripted!

Use meta-data files to describe raw and cleaned data.
* structure as data (e.g., `.csv`) so easy to read

???

The generation of the raw data may be the one thing out of your control in an analysis. But from the time the data are passed on to you, everything that happens should be reproducible. 

This can be painful. For many projects, 90% of time might be devoted to wrangling raw data into a format that is usable. Save yourself from the danger of having to re-do all those painful bits when (not if) the data change.

---

### Organizing data

Hadley Wickham [defined the notion of tidy data](https://doi.org/10.18637/jss.v059.i10). 
* Each variable forms a column.
* Each observation forms a row.
* Each observational unit forms a table. 

.code-box[
| ptid | day | age | drug | out |
|------|-----|-----|------|-----|
| 1    | 1   | 28  | 0    | 0   |
| 1    | 2   | 28  | 0    | 1   |
| 2    | 1   | 65  | 0    | 0   |
| 2    | 2   | 65  | 1    | 1   |
| 3    | 1   | 34  | 0    | 0   |
| 3    | 2   | 34  | -    | 1   |
]

---

background-color: #487f84
class: title-slide, center, inverse, middle

*If the first line of your R script is*

`setwd("C:\Users\jenny\path\that\only\I\have")`

*I will come into your office and SET YOUR COMPUTER ON FIRE 🔥.*


<div> [Jenny Bryan](https://jennybryan.org/)

---

### Project-based organization

Organize each analysis into a separate *project*.
* A directory on your computer that holds all relevant files

The __project directory__ is the directory that holds all relevant files.

Any R script in the project assumes it will be run: 
* from a fresh R process 
* with working directory set to the project directory

Read [Jenny Bryan and James Hester's chapter](https://rstats.wtf/project-oriented-workflow.html) on project-oriented work-flows.

---

### The `here` package

.red[No absolute paths.]

For `R` projects, the [`here`](https://here.r-lib.org/) package provides a simple way to use relative file paths.

Each `R` script or `Rmd` report, should contain a call to `here::i_am('path/to/this/file')` at the top.
* `path/to/this/file` should be replaced with the path .green[relative] to the __project directory__.
* `here::i_am` means use function `i_am` from `here` package.

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[Updating report with here package]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="01_hiv_project.zip" style="color:#ffffff" download>Code: `01_hiv_project.zip`</a>
]

???

Demo: 
* `01_hiv_project.zip`
* Modify `hiv_report.Rmd`'s chunk labeled `load-data` to include call to `i_am`
* Update filepath accordingly
* Render document

---

### The `here` package

The call to `i_am` establishes the __project directory__.
* Subsequent file paths can be made using the `here` function.
* `here("path", "to", "folder", "file.csv)` = `[project_directory]/path/to/folder/file.csv`

You can check what `here` thinks the root directory is by printing the output of `here::here()`.

---

### Modularize code

It is common, but not best practice, to maintain all `R` code in an `Rmd` file.
* OK for small projects, but difficult to maintain

Reasons to prefer a different system:
* Faster compiling of reports
  * only update portions of report that needs updating
* Easier to locate chunks of code
* More likely to write code that can be re-used

???

R Markdown has a cache system that makes report compiling faster. However, it is somewhat rudimentary and may be considered better practice to develop your own caching system, e.g., based on `Make`. 

---

### Modularize code

Separate R data analysis into discrete tasks and have a separate R script for each.
* cleaning data
  * `code/00_clean_data.R`
* descriptive analysis
  * `code/01_table1.R`
  * `code/02_scatter.R`
* primary model
  * `code/03_models.R`

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[Modularizing code]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="02_hiv_project.zip" style="color:#ffffff" download>Code: `02_hiv_project.zip`</a>
]

???

Demo: 
* `02_hiv_project.zip`
* rename `data` to `raw_data`
* make `output` and `code` folder
* remove pieces of `hiv_report.Rmd` to `R` files
* remove `cutpoint` from `params` and instead feed arguments into script from command line
