---
title: "GNU Make"
author: "David Benkeser, PhD MPH<br> <span style = 'font-size: 50%;'> Emory University<br> Department of Biostatistics and Bioinformatics </span>"
date: 'Introduction Reproducible Workflows in R<br><br>`r renv::activate("../.."); fontawesome::fa("link", fill = '#ffffff')` [.white[bit.ly/intro_repro_workflo]](https://bit.ly/intro_repro_workflo) <br> `r fontawesome::fa("book", fill = '#ffffff')` [.white[Additional reading]](https://benkeser.github.io/intro_repro_workflo/readings#gnu-makefiles)'
tldr: "You'll never again think to yourself, 'Where the heck did this plot come from?'"
recording: ""
start: ""
breakoutsoln: ""
reading: "gnu-makefiles"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    nature:
      titleSlideClass: ["left", "middle", "inverse"]
      highlightStyle: tomorrow-night-blue
      highlightLanguage: rmarkdown
      highlightLines: false
---

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)

extra_css <- list(
  ".clearbox" = list(
    display = "inline-block", 
    width = "100%",
    padding = "5px",
    border = "1px solid #012169",
    `background-color` = "#d9d9d6",
    `align-items` = "left",
    `vertical-align` = "middle"
  ),
  ".small" =  list(`font-size` = "80%"),
  ".large" =  list(`font-size` = "150%"),
  "ul li" = list(`margin-bottom` = "10px"),
  ".red" = list(color = "#da291c",
                `font-weight` = "600"),
  ".green" = list(color = "#348338",
                `font-weight` = "600"),
  ".remark-code-line-highlighted" = list(border = "2px solid #f2a900",
                                         `background-color` = "#002451"),
  ".code-box" = list(display = "inline-block", 
    width = "95%",
    `line-height` = "0.5em",
    padding = "5px",
    `font-size` = "80%",
    `background-color` = "#f6f6f6",
    `align-items` = "left",
    `font-family` = "Courier Prime",
    border = "1px solid black"),
  "a" = list(color = "#007dba"),
  "a:hover" = list("text-decoration" = "underline")
)

style_mono_accent(
  base_color = "#012169",
  header_font_google = google_font("DM Sans"),
  text_font_google   = google_font("DM Sans", "400", "400i"),
  code_font_google   = google_font("Courier Prime"),
  extra_css = extra_css
)
```

<style type="text/css">
.remark-slide-content {
    font-size: 25px
}
</style>

## Learning objectives

1. Describe the basic logic of target updating in make.
2. Define a `PHONY` rule

## Learning objectives: redux

1. Create basic `Makefiles` that document dependencies between targets.
2. Use `make` to render an entire project from start (i.e., a clean working directory) to finish.
3. Discuss potential uses of more advanced make features.

### Why GNU Make?

GNU Make is a program often used for compiling software. 
* Building up many dependent pieces of software.

But that's exactly __what data analysis is__! 
* Analysis report &#8592; tables and figures &#8592; code &#8592; data

GNU Make is a formal system for:
* automating a workflow
  * just type `make` and hit enter!
* documenting a workflow
* documenting dependencies among data, code, results.

???

If you can effectively use `Make`, you are living the reproducible dream. Literally you will just go to the command line and type `make` and your
whole analysis will be off and running. Data get updated? Swap in the new data set and `make`. Change the code for Figure 1? `make`.

It takes time to get to this level, but this is the goal of reproducible data science. 

Remember, everything that we're doing is about making our lives easier *in the long run*. It might be convenient in the short term to:
* keep all your code in one long file,
* open the file and interactively execute code,
* copy/paste results.

But in the long run, you'll have to 
* sift through 1000s of lines of code every time you want to make a small change,
* remember the exact sequence of code that you executed six months or a year ago,
* copy/paste results 100 times!

---

### How do I make?

GNU make can be installed via:

MacOSX, through the command line toolkit.
* Open Terminal application
* Run: `xcode-select --install`

Windows, through `winget`.
* Open PowerShell application
* Run: `winget install GnuWin32.Make`
* Add installation path to `PATH`
  * Probably in `C:\Program Files (x86)\GnuWin32\bin`

---

### How does it work?

Recall, one of our derived outputs was a cleaned data set stored in `output/data_clean.rds`.
* created when we ran `code/00_clean_data.R`

A `Makefile` documents this dependency!

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[A first rule to make]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="01_make_hiv_project.zip" style="color:#ffffff">Code: `01_make_hiv_project.zip`</a>
]

???

Demo:
* `01_make_hiv_project.zip`
* make a plain text file named `Makefile`
* input the following rule:
  * `output/data_clean.rds: code/00_clean_data.R`
  *     Rscript code/00_clean_data.R
* note the use of TAB 
* type `make output/data_clean.rds` at command line

---

### How does it work?

````markdown
output/data_clean.rds: code/00_clean_data.R
    Rscript code/00_clean_data.R
````

* This is our first make __rule__
* `output/data_clean.rds` is the __target__
  * the file produced from running the code
* `code/00_clean_data.R` is a __pre-requisite__
  * a dependency of the target
* `Rscript code/00_clean_data.R` is the __action__ to take to build the target

.red[Note the use of TAB and not spaces!]

???

If you ever see the error `Makefile:3: *** missing separator.  Stop.`, you forgot to use tabs.

This is going to be an annoying aspect of this lecture -- copying and pasting code from the slides to a text editor is not guaranteed to respect tabs. 

---

### How does it work?

GNU Make logic:
* Want to make __target__, which depends on __prereq__.
* Does `target` exist? 
  * If  <em style="color:#da291c";>No</em> = execute __action__
  * <em style="color:#348338";>Yes</em> = ask, has __prereq__ changed since __target__ was last updated?
      * <em style="color:#348338";>Yes</em> = execute __action__. 
      * <em style="color:#da291c";>No</em> = take no action, __target__ is already up to date.

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[Updating targets when pre-reqs are modified]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="02_make_hiv_project.zip" style="color:#ffffff">Code: `02_make_hiv_project.zip`</a>
]

???

Demo:
* `02_make_hiv_project.zip`
* run `make` again. Note that nothing needs to update.
* update labels in `code/00_clean_data.R`
* run `make` again. Note that code executes this time
* check that labels were updated
  * use `readRDS` to load `output/data_clean.rds`
  * use `labelled::var_label(data$column_name)` to check changed labels
* add a second rule
  * `output/table1.rds: code/01_table1.R output/data_clean.rds`
  * `Rscript code/01_table1.R`
* change spanning header of table
* `make output/table1.rds`
* change more labels in `code/00_clean_data.R`
* `make output/table1.rds`

---

### More on rules

Rules do not always have to create files.
* Example: `make clean` to remove old output files

Another example: we could use `make descriptive_analysis` to run both `01_table1.R` and `02_scatter.R`
* .red[Less clear documentation]
* .green[Easier to remember?]

The bash symbols `&&` and `\` can be helpful to split commands over multiple lines.
* `&&` = only execute next command if last command runs error-free
  * needed if specific order is required for multiple actions
* `\` = escape character to ignore a new line

???

Can be nice to clean up the working directory to recreate all output of the workflow explicitly. 

Notice `clean` has no dependencies. 

---

### `PHONY` rules

Naming rules after things other than file names works fine .red[as long as there's no file] that shares the same name in the folder.

In this case, we need to tell `make` that clean is a `PHONY`.
* Example: `PHONY: clean`

???

Something to be aware of. You can generally leave off `PHONY` but good to know about it. For example, I could see a `make docs` command and a `docs` folder containing documentation. 

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[Adding PHONY rules]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="03_make_hiv_project.zip" style="color:#ffffff">Code: `03_make_hiv_project.zip`</a>
]

???

Demo:
* `03_make_hiv_project.zip`
* make a rule for `descriptive_analysis` that runs both `code/01_table1.R` and `code/02_scatter.R`
* make a rule for clean that removes all `.rds` files from output

---

### More on make
You can get very fancy with `make`.
* Automatic variable names
  * E.g., use `$<` in place of first dependency
* Pattern matching
  * E.g., `%` is a wildcard for targets and `$*` references the matched part of the target
* [Functions](https://swcarpentry.github.io/make-novice/07-functions/index.html), [variables](https://swcarpentry.github.io/make-novice/06-variables/index.html), ...

Other miscellaneous notes:
* Name your `Makefile` e.g., `something_else`
  * Then have to run `make -f something_else`
* `make` with no options builds the first rule in your `Makefile`
  * Add a rule for `all` at top?
* Add `@` at start of action to not print output from command

---

class: title-slide, center, inverse, middle
background-color: #487f84

.large[
`r fontawesome::fa("desktop", fill = "#ffffff")` .white[Finishing make rule for HIV project]
]

.large[
`r fontawesome::fa("code", fill = "#ffffff")` <a href="04_make_hiv_project.zip" style="color:#ffffff">Code: `04_make_hiv_project.zip`</a>
]

???

Demo:
* `04_make_hiv_project.zip`
* make rules for other aspects of report and the report itself
* confirm that the whole pipeline builds from scratch
